---
title: "Milestone #1"
author: "Rachael Baartmans, Lara Petalio, Christine Truong"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

Please push to GitHub a word document or PDF with the following information -

Project option selection
--
We are choosing to do Scenario 3 for our group project.


Create git repository
--
Link to our group's git repository: https://github.com/christine-truong/phw251-group-project


Roles and responsibilities
--
Team's preferred communication method (email, text, bcourse messaging, etc.):
  Text messaging. 

Team's preferred meeting times and frequency:
  We will meet every Tuesday at 6:30pm PST/9:30pm EST over Zoom unless it is not needed.
  
Future non-academic commitments that might affect members' availability:
  Work commitments, such as staying late at work, which may prevent members from being available to all get together over Zoom.

Meeting tempo (“checking in” at the beginning of meetings versus 
“just sticking to business”):
  Checking in and chatting as needed for support from other group members or updates, either over text or Zoom calls.

Team's preferred method for tracking progress:
  We have agreed to create a schedule of internal deadlines and list of tasks to complete, as well as split up the work evenly among group members during a weekly meeting before the commencement of a milestone. Throughout the weeks before a milestone is due, we will regularly check in with each other via text message on a task-by-task basis to discuss our individual progress on the project and what tasks have been successfully completed/have not been finished yet.
  
Potential dates and times to meet with a course facilitator during Weeks 3-5:
  Any weekday evening when other course activities (e.g., live sessions) are not already occurring, either for this course or PHW250B.
  
Point person for taking minutes/creating agendas from weekly meetings and contacting course facilitators with questions:
  Christine 
  
Point person(s) for submitting all milestones (depending on availability of member throughout the weeks we have submissions, which will be clearly discussed among the group before submissions):
  Lara or Rachael 

Conflict management
--
"If a conflict arises, plan to solve the issue as soon as possible. 
This is best done using synchronous (Zoom, Google Hangouts) communication rather than asynchronous (email).
If the group is unable to resolve the conflict, seek advice from the instructional team."

  We have discussed this as a group and agree to work things out among ourselves should any conflicts arise.
